services:
  gozero_db:
    image: postgres:16
    environment:
      POSTGRES_USER: gozero_user
      POSTGRES_PASSWORD: gozero_password
      POSTGRES_DB: gozero_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - db
networks:
  db:
    driver: bridge
